### ISSUE TITLE
Broken `defnifp` macro

### ISSUE THREAD

**Issue by bblaszkow06** [membraneframework/bundlex#23] opened 2018-07-18 16:14 UTC
Compilaton fails with following error:
```
== Compilation error in file lib/membrane_payload_shm_native.ex ==
** (CompileError) lib/membrane_payload_shm_native.ex:1: inlined function createp/2 undefined
    (stdlib) lists.erl:1338: :lists.foreach/2
    (stdlib) erl_eval.erl:677: :erl_eval.do_apply/6
```
Error most probably comes from after compile callback in `loader.ex`. Using defnif instead of defnifp fixes the problem

**Comment by mat-hek** [comment] 2018-07-19 10:53
This happens only if a private function is unused, and is caused by a bug in elixir https://github.com/elixir-lang/elixir/issues/7409 which seems to be going to be fixed in 1.7.0

**Closed by mat-hek** 2018-07-19 10:53 UTC
